name: test
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython
  - cnvkit
  - openpyxl
  - pysam
  - xlsxwriter
  - pandas
  # build
  - conda-build
  - pytest
  - pytest-cov
