name: test
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - boa # build package with mamba
  - biopython
  - cnvkit
  - openpyxl
  - pysam
  - xlsxwriter
  - pandas
  - conda-build
  - pytest
  - pytest-cov
