name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron:  '0 0 * * 1'

jobs:

  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: 'Deploying miniconda'
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          environment-file: recipes/workflow.yaml
          mamba-version: "*"
          channel-priority: true
          use-mamba: true
      - name: 'Build conda package'
        run: |
          conda mambabuild recipes/

  Pytest:
    needs: [Build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: 'Deploying miniconda'
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          environment-file: recipes/workflow.yaml
          mamba-version: "*"
          channel-priority: true
          use-mamba: true
      - name: 'Run tests'
        run: |
          pip install --no-deps .
          python -m pytest tests
